import { DatabaseRecords } from '../namespace';

export const initialEntities: DatabaseRecords = {
  '1': { id: '1', value: 'Node1', parentId: null, isRemoved: false },
  '2': { id: '2', value: 'Node2', parentId: '1', isRemoved: false },
  '3': { id: '3', value: 'Node3', parentId: '1', isRemoved: false },
  '4': { id: '4', value: 'Node4', parentId: '1', isRemoved: false },
  '5': { id: '5', value: 'Node5', parentId: '1', isRemoved: false },
  '6': { id: '6', value: 'Node6', parentId: '5', isRemoved: false },
  '7': { id: '7', value: 'Node7', parentId: '2', isRemoved: false },
  '8': { id: '8', value: 'Node8', parentId: '2', isRemoved: false },
  '9': { id: '9', value: 'Node9', parentId: '2', isRemoved: false },
  '10': { id: '10', value: 'Node10', parentId: '7', isRemoved: false },
  '11': { id: '11', value: 'Node11', parentId: '7', isRemoved: false },
  '12': { id: '12', value: 'Node12', parentId: '7', isRemoved: false },
  '13': { id: '13', value: 'Node13', parentId: '11', isRemoved: false },
  '14': { id: '14', value: 'Node14', parentId: '11', isRemoved: false },
  '15': { id: '15', value: 'Node15', parentId: '11', isRemoved: false },
  '16': { id: '16', value: 'Node16', parentId: '11', isRemoved: false },
  '17': { id: '17', value: 'Node17', parentId: '15', isRemoved: false },
  '18': { id: '18', value: 'Node18', parentId: '3', isRemoved: false },
  '19': { id: '19', value: 'Node19', parentId: '3', isRemoved: false },
  '20': { id: '20', value: 'Node20', parentId: '18', isRemoved: false },
  '21': { id: '21', value: 'Node21', parentId: '18', isRemoved: false },
  '22': { id: '22', value: 'Node22', parentId: '3', isRemoved: false },
  '23': { id: '23', value: 'Node23', parentId: '3', isRemoved: false },
  '24': { id: '24', value: 'Node24', parentId: '3', isRemoved: false },
  '25': { id: '25', value: 'Node25', parentId: '24', isRemoved: false },
  '26': { id: '26', value: 'Node26', parentId: '3', isRemoved: false },
  '27': { id: '27', value: 'Node27', parentId: '26', isRemoved: false },
  '28': { id: '28', value: 'Node28', parentId: '16', isRemoved: false },
  '29': { id: '29', value: 'Node29', parentId: '16', isRemoved: false },
  '30': { id: '30', value: 'Node30', parentId: '16', isRemoved: false },
};
